### ISSUE TITLE
Undefined local variable or method `url' for Codacy::ClientAPI:Module while pushing results

### ISSUE THREAD

**Issue by gianlucarizzo** [codacy/ruby-codacy-coverage#35]
Hi,
i tried to send my coverage report without success. 
I followed the readme instructions, added the env key correctly, but this error appears while connecting to the service

```
# Running:

......

Finished in 1.807026s, 3.3204 runs/s, 11.6213 assertions/s.

6 runs, 21 assertions, 0 failures, 0 errors, 0 skips
I, [2018-08-11T15:28:36.376402 #23350]  INFO -- : Parsing simplecov result to Codacy format...
I, [2018-08-11T15:28:36.376981 #23350]  INFO -- : Preparing payload...
F, [2018-08-11T15:28:36.380083 #23350] FATAL -- : undefined local variable or method `url' for Codacy::ClientAPI:Module
Did you mean?  URI (NameError)
/home/gianluca/.rvm/gems/ruby-2.3.3/gems/codacy-coverage-2.0.0/lib/codacy/client.rb:25:in `post_results'
/home/gianluca/.rvm/gems/ruby-2.3.3/gems/codacy-coverage-2.0.0/lib/codacy/formatter.rb:7:in `format'
/home/gianluca/.rvm/gems/ruby-2.3.3/gems/simplecov-0.16.1/lib/simplecov/result.rb:48:in `format!'
/home/gianluca/.rvm/gems/ruby-2.3.3/gems/simplecov-0.16.1/lib/simplecov/configuration.rb:182:in `block in at_exit'
/home/gianluca/.rvm/gems/ruby-2.3.3/gems/simplecov-0.16.1/lib/simplecov.rb:200:in `run_exit_tasks!'
/home/gianluca/.rvm/gems/ruby-2.3.3/gems/simplecov-0.16.1/lib/simplecov/defaults.rb:27:in `block in <top (required)>'
```

this error occurs with this implementation in `test_helper.rb` (where i try to use both coveralls and codacy reporting system [here](https://github.com/gianlucarizzo/opswatch/blob/ecc3bc0f6b92400c6995365ac6fa4230f654daf6/test/test_helper.rb) ) and even with this minimal implementation 
```
require 'codacy-coverage'
Codacy::Reporter.start

require 'opswatch'
require 'minitest/autorun'

$LOAD_PATH.unshift File.expand_path('../lib', __dir__)
GEM_ROOT = File.expand_path('..', __dir__)
```

**Comment by rtfpessoa** [comment]
Thanks for reporting this problem @gianlucarizzo.
Sorry for the trouble. Should be fixed in #36 released as version `2.0.1`.
